### PR TITLE
Use JSoup for HTML parsing

### PR DESCRIPTION
**Pull request by defer**
HTML parsing is very error prone. OpenSpritz is using Android's HTML and then applying a regex. This has multiple problems:
- CSS is not properly parsed
- There is no guarantee that the regex properly filters HTML.

Enter JSoup, it understands the tree and can make more informed decisions. Additionally it has a clean method which is exactly what we want.

When proguarded this adds ~80kb to the final APK.

### CODE REVIEW

**Comment by defer** [comment]
This includes the changes from #32

**Comment by andrewgiang** [comment]
Jsoup can also be use to parse web content if you plan to add that later on. 

Do the Jsoup changes depend on the previous pull request? If not, I think you should cherry pick them to a separate branch and re submit the request.

**Comment by defer** [comment]
Not really, there are some intersections but they can be easily resolved.

I am doing a slightly larger refactor that extracts e-pub specific logic from EpubSpritzer and hopefully lays grounds for generic format support. It will be easier to incorporate both this change and the other in the new refactor.

**Comment by OnlyInAmerica** [comment]
Manually merged in d7d2cdf. 

Actually had to remove Jsoup due to performance issues on large chapters, but the other changes were all good. Instead a quick hack of substringing the epub string on "<body" if that exists seems to be a very fast and effective way of stripping css without expensive inspection.

**Pull request closed without merging**
