### PR TITLE
Refactor Epub-logic, better TOC support.

### PR DESCRIPTION
**Pull request by defer**
This uses the Table of contents instead of spines. On my EPubs this provides a more consistent experience with titles, they are available more often than not.

### CODE REVIEW

**Comment by andrewgiang** [comment]
Just wondering if this would cause problems with epubs without a toc?

**Comment by defer** [comment]
I share your concern. Usually a TOC is better than using spines. What about a fallback behavior?

Try to use TOC if it exists, otherwise fallback to spines. This would be nearly trivial to implement, what do you think?

**Comment by andrewgiang** [comment]
That would be the route I would take. We want to be able to give the best experience no matter what epub is thrown at the app.

**Comment by defer** [comment]
Please read the commit message from the change above. I think this is a nice step forward.

We could add MOBI or HTML or any format tomorrow just by implementing a class and adding the new entry point.

**Comment by OnlyInAmerica** [comment]
Manually merged in d7d2cdff

**Comment by defer** [comment]
When you manually merge you should keep the author (--author in the git prompt). Don't worry about it though, I don't mind, but it's usually considered good etiquette.

Thanks for merging.

**Comment by OnlyInAmerica** [comment]
Absolutely, sorry! I accidentally ran a `rm` that affected files in my local repo's `.git/` and broke my local history. I'd let too much work pile up to repeat, so I combined it all into a single commit. FWIW I added you all to the README.

**Comment by defer** [comment]
Let me just abuse this comment thread.

This is now in a state where I can use it. Do you have any plans going forward? I wouldn't mind contributing more to the project but basically my needs are served.

**Comment by IniTW8X** [comment]
I don't know about today's changes, but from last apk I noticed the chapters still buggy. Fix the natural progression through book and I would be happy too :)
Now, when one chapter naturally finishes, instead of continuing with the next one, it skips back.

**Comment by OnlyInAmerica** [comment]
@IniTW8X Agreed. There's also the problem of some chapters containing data that won't be displayed, and it's tricky to determine that efficiently before presenting them in the chapter select DialogFragment.

Some other thoughts:
- SpritzerTextView should ensure text doesn't wrap to the next line. Spritzer#MAX_WORD_LENGTH is fine for general-purpose use, but the SpritzerTextView implementation should be more intelligent as it's aware of text size and it's own layout_width.
- Handling HTTP:// and generic text content. We can use [Readability's Parser API](https://www.readability.com/developers/api/parser) to get the plain text content from URLs shared to the app.
- (Far out) Use Android's System Alert Window feature to draw the SpritzerTextView over other apps. That way I can "share" a url from Chrome and have OpenSpritz do it's thing right on top of Chrome, instead of bouncing me to a fullscreen app experience.

**Comment by IniTW8X** [comment]
Also, noticed apk is missing :(

**Comment by OnlyInAmerica** [comment]
Unfortunately, bundling an apk with each release unnecessarily inflates the
size of the repository and increases the hassle for contributors. I'm
always trying to make the build instructions as simple as possible, and
we'll publish on Google Play once we're in a stable spot.

**Comment by nightscape** [comment]
Maybe publishing on Bintray would be an option so you don't have to put
binaries into git.
 Am 18.03.2014 17:10 schrieb "David Brodsky" notifications@github.com:

> Unfortunately, bundling an apk with each release unnecessarily inflates
> the
> size of the repository and increases the hassle for contributors. I'm
> always trying to make the build instructions as simple as possible, and
> we'll publish on Google Play once we're in a stable spot.
>

**Comment by andrewgiang** [comment]
Not sure on the implementation details but if you wanted to do something like what @nightscape is suggesting you could run a travis-ci instance that will compile, run tests, and upload to a website.

**Pull request closed without merging**
