### PR TITLE
Guidelines and Pivot  + Default Click Listener 

### PR DESCRIPTION
**Pull request by andrewgiang**
This pull request adds a few things:
1. Automatic drawing of guidelines and pivot( you won't have add two extra TextViews to show guidelines)
2. An xml attr clickControls which if set to true will allow the user to pause or play by clicking on the TextView

### CODE REVIEW

**Comment by OnlyInAmerica** [comment]
This is a great idea. I made a few changes while merging:
1. The logic behind calculating `centerX`:
   
   ```
   final float centerX = textSize * 2 + getPaddingLeft();
   ```
   
   became: 
   
   ```
   float centerX = calculatePivotXOffset() + getPaddingLeft();
   ...
   private float calculatePivotXOffset() {
   // Craft a test String of precise length
   // to reach pivot character
   if (mTestString == null) {
       // Spritzer requires monospace font so character is irrelevant
       mTestString = "a";
   }
   // Measure the rendered distance of CHARS_LEFT_OF_PIVOT chars
   // plus half the pivot character
   return (getPaint().measureText(mTestString, 0, 1) * (Spritzer.CHARS_LEFT_OF_PIVOT + .50f));
   ```
   
   }
2. Guide bars: As is, the guide bars appears like so on my N5:

orig guide bars

I made some adjustments to make the guides a bit simpler:

new guide bars

**Comment by andrewgiang** [comment]
Great addition, was wondering how to measure the pivot accurately. This would only work for monospace fonts correct?

**Comment by OnlyInAmerica** [comment]
It can be adjusted for non monospace fonts by changing  `calculatePivotXOffset` to return: 

```
getPaint().measureText(getText(), 0, Spritzer.CHARS_LEFT_OF_PIVOT + 1)*
```

But using non-monospace fonts would be a pain because then `calculatePivotXOffset` would return different values for every unique character combination, instead of only on Text style changes (with monospace). Therefore we'd have to hack-pad each spritz string uniquely to make sure the pivot character remained stationary.

 *To be spot-on it'd actually be the width of Spritzer.CHARS_LEFT_OF_PIVOT chars plus half the width of the pivot char.

**Comment by IniTW8X** [comment]
Just installed the latest .apk and the new guidelines are merging, blending in with the words (see screenshot)
screenshot_2014-03-10-07-11-56

**Comment by andrewgiang** [comment]
What device are you using? Also I'm working on automatically setting the pivot length and the padding based on the font metrics. 

You can view a preview here: http://www.youtube.com/watch?v=rossRSokq4Y

**Comment by IniTW8X** [comment]
It's Asus MemoPad HD 7 ME173X.
//BTW: after testing the app yesterday and today, the most annoying thing I found was the fact that when system "kills" the app to save RAM (spritz is in background), when I run the app again it does not remember the place in the book I was. It asks to load epub again. This is a bit problem for epubs that have broken chapters, so... But I know that you are now trying to set the basics up.

**Comment by OnlyInAmerica** [comment]
@IniTW8X Thanks for the report. Fixes in b7c2127 may resolve your issue, thanks in good part to andrewgiang.

**Comment by IniTW8X** [comment]
Thanks, and even more thanks for the saveState function! :)
//Edit: It does save state, but when I kill the app and restart it, it is not on right position it was previously on (Chapter 2, 28 minutes remaining, after restarting Chapter 2, 1 minute remaining). Could be problem with the epub though, so I just keep testing.

**Pull request merged**
